recipes/urls.py
from django.urls import path, re_path, register_converter
from . import views
from . import converters

register_converter(converters.FourDigitYearConverter, "year4")

urlpatterns = [
    path('', views.RecipeHome.as_view(), name='home'),  # http://127.0.0.1:8000
    path('about/', views.about, name='about'),
    path('addpage/', views.AddPage.as_view(), name='add_page'),
    path('login/', views.login, name='login'),
    path('post/<slug:post_slug>/', views.ShowPost.as_view(), name='post'),
    path('category/<slug:cat_slug>/', views.RecipeCategory.as_view(), name='category'),
    path('tag/<slug:tag_slug>/', views.TagPostList.as_view(), name='tag'),
    path('edit/<slug:slug>/', views.UpdatePage.as_view(), name='edit_page'),
]

recipesite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from recipes import views
from recipes.views import page_not_found
from recipesite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('__debug__/', include('debug_toolbar.urls'))
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



handler404 = page_not_found

admin.site.site_header = 'Панель администрирования'
admin.site.index_title = 'Кулинарные рецепты'

users/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeView, \
    PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from . import views

app_name = 'users'

urlpatterns = [
    path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('password-change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'), name='password_change_done'),
    path('password-reset/', PasswordResetView.as_view(
        template_name='users/password_reset_form.html',
        email_template_name='users/password_reset_email.html',
        success_url=reverse_lazy('users:password_reset_done')),
        name='password_reset'),
    path('password-reset/done/', PasswordResetDoneView.as_view(
        template_name='users/password_reset_done.html'),
        name='password_reset_done'),
    path('password-reset/<uidb64>/<token>', PasswordResetConfirmView.as_view(
        template_name='users/password_reset_confirm.html',
        success_url=reverse_lazy('users:password_reset_complete')),
        name='password_reset_confirm'),
    path('password-reset/complete/', PasswordResetCompleteView.as_view(
        template_name='users/password_reset_complete.html'),
        name='password_reset_complete'),
    path('register/', views.RegisterUser.as_view(), name='register'),
    path('profile/', views.ProfileUser.as_view(), name='profile'),
]

recipes/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(
            is_published=Recipe.Status.PUBLISHED)


class Recipe(models.Model):
    class Status(models.IntegerChoices):
        DRAFT = 0, 'Черновик'
        PUBLISHED = 1, 'Опубликовано'

    title = models.CharField(max_length=255, verbose_name='Заголовок')
    slug = models.SlugField(
        max_length=255, unique=True, db_index=True, verbose_name='Slug')
    content = models.TextField(blank=True, verbose_name='Текст рецепта')
    photo = models.ImageField(
        upload_to='photos/%Y/%m/%d/', default=None, blank=True, null=True,
        verbose_name='Фото')
    time_create = models.DateTimeField(
        auto_now_add=True, verbose_name='Время создания')
    time_update = models.DateTimeField(
        auto_now=True, verbose_name='Время изменения')
    is_published = models.BooleanField(
        choices=tuple(map(lambda x: (bool(x[0]), x[1]), Status.choices)),
        default=Status.DRAFT, verbose_name='Статус')
    cat = models.ForeignKey(
        'Category', on_delete=models.PROTECT,
        related_name='posts', verbose_name='Категории')
    tags = models.ManyToManyField(
        'TagPost', blank=True, related_name='tags', verbose_name='Теги')
    author = models.ForeignKey(
        get_user_model(), on_delete=models.SET_NULL,
        related_name='posts', null=True, default=None)

    objects = models.Manager()
    published = PublishedManager()

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
        ordering = ['-time_create']
        indexes = [
            models.Index(fields=['-time_create'])
        ]

    def get_absolute_url(self):
        return reverse('post', kwargs={'post_slug': self.slug})


class Category(models.Model):
    objects = None
    name = models.CharField(max_length=100, db_index=True, verbose_name='Категория')
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('category', kwargs={'cat_slug': self.slug})


class TagPost(models.Model):
    objects = None
    tag = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=255, unique=True, db_index=True)

    def __str__(self):
        return self.tag

    def get_absolute_url(self):
        return reverse('tag', kwargs={'tag_slug': self.slug})


class UploadFiles(models.Model):
    file = models.FileField(upload_to='uploads_model')

recipes/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.utils.deconstruct import deconstructible

from .models import Category, Recipe


@deconstructible
class RussianValidator:
    ALLOWED_CHARS = ('АБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЬЫЪЭЮЯабвгдеёжз'
                     'ийклмнопрстуфхцчшщьыъэюя0123456789- ')
    code = 'russian'

    def __init__(self, message=None):
        self.message = message if message else ('Должны присутствовать '
                                                'только русские символы, '
                                                'дефис и пробел.')

    def __call__(self, value, *args, **kwargs):
        if not (set(value) <= set(self.ALLOWED_CHARS)):
            raise ValidationError(self.message, code=self.code)


class AddPostForm(forms.ModelForm):
    cat = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        empty_label='Категория не выбрана', label='Категория')

    class Meta:
        model = Recipe
        fields = ['title', 'slug', 'content',
                  'photo', 'is_published', 'cat', 'tags']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-input'}),
            'content': forms.Textarea(attrs={'cols': 50, 'rows': 5}),
        }
        labels = {'slug': 'URL'}

    def clean_title(self):
        title = self.cleaned_data['title']
        if len(title) > 50:
            raise ValidationError('Длина превышает 50 символов')

        return title


class UploadFileForm(forms.Form):
    file = forms.ImageField(label='Файл')

recipes/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator
from django.http import HttpResponse, HttpResponseNotFound, Http404, \
    HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.template.loader import render_to_string
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, \
    CreateView, UpdateView

from .forms import AddPostForm, UploadFileForm
from .models import Recipe, Category, TagPost, UploadFiles
from .utils import DataMixin


class RecipeHome(DataMixin, ListView):
    template_name = 'recipe/index.html'
    context_object_name = 'posts'
    title_page = 'Главная страница'
    cat_selected = 0

    def get_queryset(self):
        return Recipe.published.all().select_related('cat')


def about(request):
    contact_list = Recipe.published.all()
    paginator = Paginator(contact_list, 3)

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    return render(request, 'recipe/about.html',
                  {'title': 'О сайте', 'page_obj': page_obj})


class ShowPost(DataMixin, DetailView):
    template_name = 'recipe/post.html'
    slug_url_kwarg = 'post_slug'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return self.get_mixin_context(context, title=context['post'].title)

    def get_object(self, queryset=None):
        return get_object_or_404(
            Recipe.published, slug=self.kwargs[self.slug_url_kwarg])


class AddPage(LoginRequiredMixin, DataMixin, CreateView):
    form_class = AddPostForm
    template_name = 'recipe/addpage.html'
    title_page = 'Добавление рецепта'

    def form_valid(self, form):
        r = form.save(commit=False)
        r.author = self.request.user
        return super().form_valid(form)


class UpdatePage(DataMixin, UpdateView):
    model = Recipe
    fields = ['title', 'content', 'photo', 'is_published', 'cat']
    template_name = 'recipe/addpage.html'
    success_url = reverse_lazy('home')
    title_page = 'Редактирование рецепта'


def login(request):
    return HttpResponse("Авторизация")


class RecipeCategory(DataMixin, ListView):
    template_name = 'recipe/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_queryset(self):
        return Recipe.published.filter(
            cat__slug=self.kwargs['cat_slug']).select_related('cat')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cat = context['posts'][0].cat
        return self.get_mixin_context(context,
                                      title='Категория - ' + cat.name,
                                      cat_selected=cat.pk,
                                      )


def page_not_found(request, exception):
    return HttpResponseNotFound("<h1>Страница не найдена</h1>")


class TagPostList(DataMixin, ListView):
    template_name = 'recipe/index.html'
    context_object_name = 'posts'
    allow_empty = False

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        tag = TagPost.objects.get(slug=self.kwargs['tag_slug'])
        return self.get_mixin_context(context, title='Тег: ' + tag.tag)

    def get_queryset(self):
        return Recipe.published.filter(
            tags__slug=self.kwargs['tag_slug']).select_related('cat')

recipes/templates/recipe/about.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ title }}</h1>
<p>Сайт разработан для итоговой работы на платформе GeekBrains.</p>
<p>Студент - Чуриков Сергей Викторович.</p>
{% endblock %}

recipes/templates/recipe/addpage.html
{% extends 'base.html' %}

{% block content %}
<h1>{{title}}</h1>
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-error">{{ form.non_field_errors }}</div>
    {% for f in form %}
    <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
    <div class="form-error">{{ f.errors }}</div>
    {% endfor %}
    <p><button type="submit">Отправить</button> </p>
</form>
{% endblock %}

recipes/templates/recipe/index.html
{% extends 'base.html' %}

{% block content %}
<ul class="list-articles">
	{% for p in posts %}
			<li><div class="article-panel">
	<p class="first">Категория: {{p.cat.name}} | автор:
	{{ p.author.username|default:"неизвестен" }}</p>
	<p class="last">Дата: {{p.time_update|date:"d-m-Y H:i:s"}}</p>
	</div>
{% if p.photo %}
		<p><img class="img-article-left thumb" src="{{p.photo.url}}"></p>
{% endif %}

				<h2>{{p.title}}</h2>
    {% autoescape off %}
	{{p.content|linebreaks|truncatewords:40}}
    {% endautoescape %}
			<div class="clear"></div>
			<p class="link-read-post"><a href="{{ p.get_absolute_url }}">Читать рецепт</a></p>
			</li>
	{% endfor %}
</ul>
{% endblock %}

{% block navigation %}
{% if page_obj.has_other_pages %}
<nav class="list-pages">
    <ul>
		{% if page_obj.has_previous %}
		<li class="page-num">
			<a href="?page={{ page_obj.previous_page_number }}">&lt;</a>
		</li>
		{% endif %}

        {% for p in paginator.page_range %}
		{% if page_obj.number == p %}
		<li class="page-num page-num-selected">{{ p }}</li>
		{% elif p >= page_obg.number|add:-2 and p <=  page_obg.number|add:2 %}
        <li class="page-num">
            <a href="?page={{ p }}">{{ p }}</a>
        </li>
		{% endif %}
        {% endfor %}

		{% if page_obj.has_next %}
		<li class="page-num">
			<a href="?page={{ page_obj.next_page_number }}">&gt;</a>
		</li>
		{% endif %}
    </ul>
</nav>
{% endif %}
{% endblock %}

recipes/templates/recipe/list_categories.html
{% for cat in cats %}
    {% if cat.id == cat_selected %}
    <li class="selected">{{cat.name}}</li>
    {% else %}
    <li><a href="{{ cat.get_absolute_url }}">{{cat.name}}</a></li>
    {% endif %}
{% endfor %}

recipes/templates/recipe/list_tags.html
{% if tags %}
    <p>Теги:</p>
    <ul class="tags-list">
        {% for t in tags %}
        <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a> </li>
        {% endfor %}
    </ul>
{% endif %}

recipes/templates/recipe/post.html
{% extends 'base.html' %}

{% block breadcrumbs %}
{% if perms.recipes.change_recipe %}
<p><a href="{% url 'edit_page' post.slug %}">Редактировать</a></p>
{% endif %}

<!-- Теги -->
{% with post.tags.all as tags %}
{% if tags %}
<ul class="tags-list">
    <li>Теги:</li>
    {% for t in tags %}
    <li><a href="{{t.get_absolute_url}}">{{t.tag}}</a></li>
    {% endfor %}
</ul>
{% endif %}
{% endwith %}
{% endblock %}


{% block content %}
<h1>{{post.title}}</h1>

{% if post.photo %}
<p><img class="img-article-left" src="{{post.photo.url}}"></p>
{% endif %}

{{post.content|linebreaks}}
{% endblock %}